insert into public.kur_struktur (tahun_ajaran,tingkat,program,mapel_id,jp_minggu,aktif)
select '2026/2027',v.t,v.p,m.id,v.jp,true from (values
(10,'*','Bahasa Indonesia',4),
(10,'*','Bahasa Inggris',4),
(10,'*','Bahasa Sunda',2),
(10,'BP','Dasar-Dasar Broadcasting dan Perfilman',12),
(10,'TE','Dasar-Dasar Teknik Elektronika',12),
(10,'TJKT','Dasar-Dasar Teknik Jaringan Komputer dan Telekomunikasi',12),
(10,'TP','Dasar-Dasar Teknik Mesin',12),
(10,'TO','Dasar-Dasar Teknik Otomotif',12),
(10,'*','Informatika',4),
(10,'*','Matematika',4),
(10,'*','Pendidikan Agama Islam dan Budi Pekerti',3),
(10,'*','Pendidikan Jasmani, Olahraga, dan Kesehatan',3),
(10,'*','Pendidikan Pancasila',2),
(10,'*','Projek IPAS',6),
(10,'*','Sejarah',2),
(10,'*','Seni Budaya',2),
(11,'*','Bahasa Indonesia',3),
(11,'*','Bahasa Inggris',4),
(11,'*','Kreativitas, Inovasi, dan Kewirausahaan',5),
(11,'*','Mata Pelajaran Pilihan',4),
(11,'*','Matematika',3),
(11,'*','Pendidikan Agama Islam dan Budi Pekerti',3),
(11,'*','Pendidikan Jasmani, Olahraga, dan Kesehatan',2),
(11,'*','Pendidikan Pancasila',2),
(11,'BP','Produksi Film',18),
(11,'*','Sejarah',2),
(11,'*','Seni Musik Karawitan Sunda',2),
(11,'TE','Teknik Elektronika',18),
(11,'TO','Teknik Kendaraan Ringan',18),
(11,'TJKT','Teknik Komputer dan Jaringan',18),
(11,'TP','Teknik Pemesinan',18),
(12,'*','Bahasa Indonesia',3),
(12,'*','Bahasa Inggris',4),
(12,'*','Kreativitas, Inovasi, dan Kewirausahaan',5),
(12,'*','Mata Pelajaran Pilihan',4),
(12,'*','Matematika',3),
(12,'*','Pendidikan Agama Islam dan Budi Pekerti',3),
(12,'*','Pendidikan Pancasila',2),
(12,'BP','Produksi Film',22),
(12,'TE','Teknik Elektronika',22),
(12,'TO','Teknik Kendaraan Ringan',22),
(12,'TJKT','Teknik Komputer dan Jaringan',22),
(12,'TP','Teknik Pemesinan',22)
) v(t,p,mapel,jp) join public.kur_mapel m on m.nama=v.mapel
on conflict (tahun_ajaran,tingkat,program,mapel_id) do update set jp_minggu=excluded.jp_minggu, aktif=true;
select count(*) filter (where aktif) from public.kur_struktur;