update public.kur_struktur st set jp_minggu = st.jp_minggu - 1
 from public.kur_mapel m
 where m.id = st.mapel_id and st.tahun_ajaran = '2026/2027' and st.aktif
   and (st.tingkat, st.program, m.nama) in ((10,'BP','Dasar-Dasar Broadcasting dan Perfilman'),(10,'TE','Dasar-Dasar Teknik Elektronika'),(10,'TJKT','Dasar-Dasar Teknik Jaringan Komputer dan Telekomunikasi'),(10,'TP','Dasar-Dasar Teknik Mesin'),(10,'TO','Dasar-Dasar Teknik Otomotif'),
                                          (11,'BP','Produksi Film'),(11,'TE','Teknik Elektronika'),(11,'TJKT','Teknik Komputer dan Jaringan'),(11,'TP','Teknik Pemesinan'),(11,'TO','Teknik Kendaraan Ringan'));
with mp(c,n) as (values ('m01','Dasar-Dasar Teknik Elektronika'),('m02','Teknik Elektronika'),('m03','Kreativitas, Inovasi, dan Kewirausahaan'),('m04','Mata Pelajaran Pilihan'),('m05','Dasar-Dasar Teknik Mesin'),('m06','Teknik Pemesinan'),('m07','Teknik Komputer dan Jaringan'),('m08','Pendidikan Pancasila'),('m09','Bahasa Sunda'),('m10','Dasar-Dasar Broadcasting dan Perfilman'),('m11','Bahasa Indonesia'),('m12','Teknik Kendaraan Ringan'),('m13','Pendidikan Agama Islam dan Budi Pekerti'),('m14','Dasar-Dasar Teknik Jaringan Komputer dan Telekomunikasi'),('m15','Produksi Film'),('m16','Dasar-Dasar Teknik Otomotif'),('m17','Matematika'),('m18','Pendidikan Jasmani, Olahraga, dan Kesehatan'),('m19','Informatika'),('m20','Projek IPAS'),('m21','Seni Budaya'),('m22','Seni Musik Karawitan Sunda'),('m23','Bahasa Inggris'),('m24','Sejarah')), gu(c,n) as (values ('02','kusnadi'),('03','imas samsiah'),('04','ujang ridwan maulana'),('05','jaman marpaung'),('06','arif budiman'),('07','rayuli'),('08','siti hasanah hs'),('09','mansyur'),('11','sri rahayu ningsih'),('12','nuning setiawati'),('13','aryu apendi'),('14','abdul muttaqin'),('15','joko prihanto'),('16','didi suryadi'),('17','miftahudin'),('18','siti zukhaeriyah'),('19','novalia hutabarat'),('20','muhidin'),('21','rahmat sunarya, st'),('22','ayes muharam'),('23','adung abdul haer'),('24','bangkit ismoyo'),('25','herman hardiansyah'),('26','sri sumarni'),('27','mohamad syahroni'),('28','andika pratama'),('29','irfan abdul gaffar siddiq'),('30','selvi zanita putri'),('31','yesri hilal'),('32','syaiful amri'),('33','siti jamilah'),('34','alin yuliandari'),('35','ariyanto'),('36','wahidin'),('37','budi setiawan'),('38','wawah munawaroh'),('39','endi'),('40','suryanto'),('41','siti nurhasanah'),('42','sawitri rosdiarti'),('43','jois mayasari'),('44','riki rusmana'),('45','agung suhantoro'),('46','kusno rahayu'),('47','imas pebrianti putri'),('48','kurniawan'),('49','helmy zatmika'),('50','rafika insani rahesti'),('51','dadi jaenudin'),('52','mohamad rizki sabarudin')), d(r,m,g) as (values ('X BP 1','m10','11'),('X BP 2','m10','11'),('X TE 1','m01','02'),('X TE 2','m01','02'),('X TJKT 1','m14','15'),('X TJKT 2','m14','15'),('X TJKT 3','m14','15'),('X TO 1','m16','20'),('X TO 2','m16','20'),('X TP 1','m05','06'),('X TP 2','m05','06'),('XI BP 1','m15','19'),('XI BP 2','m15','19'),('XI TE 1','m02','02'),('XI TE 2','m02','02'),('XI TJKT 1','m07','35'),('XI TJKT 2','m07','07'),('XI TJKT 3','m07','22'),('XI TO 1','m12','20'),('XI TO 2','m12','13'),('XI TP 1','m06','52'),('XI TP 2','m06','52'))
update public.kur_beban b set jp = b.jp - 1
  from d join mp on mp.c = d.m join gu on gu.c = d.g
  join public.rombel r on r.nama = d.r and r.jenis_rombel = 'Kelas Utama' and r.semester_id = '20261'
  join public.kur_mapel mm on mm.nama = mp.n join public.ptk p on lower(p.nama) = gu.n
 where b.rombel_id = r.id and b.mapel_id = mm.id and b.ptk_id = p.id and b.jp > 1;
select (select count(*) from public.kur_beban where jp = 0) beban_nol, (select sum(jp) from public.kur_beban) total_jp;